// Code generated by ent, DO NOT EDIT.

package account

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChainID holds the string denoting the chain_id field in the database.
	FieldChainID = "chain_id"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldSalt holds the string denoting the salt field in the database.
	FieldSalt = "salt"
	// FieldDeployed holds the string denoting the deployed field in the database.
	FieldDeployed = "deployed"
	// FieldDeployTxHash holds the string denoting the deploy_tx_hash field in the database.
	FieldDeployTxHash = "deploy_tx_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the account in the database.
	Table = "accounts"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldChainID,
	FieldAddress,
	FieldSalt,
	FieldDeployed,
	FieldDeployTxHash,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDeployed holds the default value on creation for the "deployed" field.
	DefaultDeployed bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Account queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChainID orders the results by the chain_id field.
func ByChainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChainID, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// BySalt orders the results by the salt field.
func BySalt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSalt, opts...).ToFunc()
}

// ByDeployed orders the results by the deployed field.
func ByDeployed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeployed, opts...).ToFunc()
}

// ByDeployTxHash orders the results by the deploy_tx_hash field.
func ByDeployTxHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeployTxHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
