// Code generated by ent, DO NOT EDIT.

package account

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/byunyourim/stablecoinbc-adapter/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldID, id))
}

// ChainID applies equality check predicate on the "chain_id" field. It's identical to ChainIDEQ.
func ChainID(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldChainID, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAddress, v))
}

// Salt applies equality check predicate on the "salt" field. It's identical to SaltEQ.
func Salt(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSalt, v))
}

// Deployed applies equality check predicate on the "deployed" field. It's identical to DeployedEQ.
func Deployed(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDeployed, v))
}

// DeployTxHash applies equality check predicate on the "deploy_tx_hash" field. It's identical to DeployTxHashEQ.
func DeployTxHash(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDeployTxHash, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// ChainIDEQ applies the EQ predicate on the "chain_id" field.
func ChainIDEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldChainID, v))
}

// ChainIDNEQ applies the NEQ predicate on the "chain_id" field.
func ChainIDNEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldChainID, v))
}

// ChainIDIn applies the In predicate on the "chain_id" field.
func ChainIDIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldChainID, vs...))
}

// ChainIDNotIn applies the NotIn predicate on the "chain_id" field.
func ChainIDNotIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldChainID, vs...))
}

// ChainIDGT applies the GT predicate on the "chain_id" field.
func ChainIDGT(v int64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldChainID, v))
}

// ChainIDGTE applies the GTE predicate on the "chain_id" field.
func ChainIDGTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldChainID, v))
}

// ChainIDLT applies the LT predicate on the "chain_id" field.
func ChainIDLT(v int64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldChainID, v))
}

// ChainIDLTE applies the LTE predicate on the "chain_id" field.
func ChainIDLTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldChainID, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldAddress, v))
}

// SaltEQ applies the EQ predicate on the "salt" field.
func SaltEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSalt, v))
}

// SaltNEQ applies the NEQ predicate on the "salt" field.
func SaltNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldSalt, v))
}

// SaltIn applies the In predicate on the "salt" field.
func SaltIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldSalt, vs...))
}

// SaltNotIn applies the NotIn predicate on the "salt" field.
func SaltNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldSalt, vs...))
}

// SaltGT applies the GT predicate on the "salt" field.
func SaltGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldSalt, v))
}

// SaltGTE applies the GTE predicate on the "salt" field.
func SaltGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldSalt, v))
}

// SaltLT applies the LT predicate on the "salt" field.
func SaltLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldSalt, v))
}

// SaltLTE applies the LTE predicate on the "salt" field.
func SaltLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldSalt, v))
}

// SaltContains applies the Contains predicate on the "salt" field.
func SaltContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldSalt, v))
}

// SaltHasPrefix applies the HasPrefix predicate on the "salt" field.
func SaltHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldSalt, v))
}

// SaltHasSuffix applies the HasSuffix predicate on the "salt" field.
func SaltHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldSalt, v))
}

// SaltEqualFold applies the EqualFold predicate on the "salt" field.
func SaltEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldSalt, v))
}

// SaltContainsFold applies the ContainsFold predicate on the "salt" field.
func SaltContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldSalt, v))
}

// DeployedEQ applies the EQ predicate on the "deployed" field.
func DeployedEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDeployed, v))
}

// DeployedNEQ applies the NEQ predicate on the "deployed" field.
func DeployedNEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldDeployed, v))
}

// DeployTxHashEQ applies the EQ predicate on the "deploy_tx_hash" field.
func DeployTxHashEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDeployTxHash, v))
}

// DeployTxHashNEQ applies the NEQ predicate on the "deploy_tx_hash" field.
func DeployTxHashNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldDeployTxHash, v))
}

// DeployTxHashIn applies the In predicate on the "deploy_tx_hash" field.
func DeployTxHashIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldDeployTxHash, vs...))
}

// DeployTxHashNotIn applies the NotIn predicate on the "deploy_tx_hash" field.
func DeployTxHashNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldDeployTxHash, vs...))
}

// DeployTxHashGT applies the GT predicate on the "deploy_tx_hash" field.
func DeployTxHashGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldDeployTxHash, v))
}

// DeployTxHashGTE applies the GTE predicate on the "deploy_tx_hash" field.
func DeployTxHashGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldDeployTxHash, v))
}

// DeployTxHashLT applies the LT predicate on the "deploy_tx_hash" field.
func DeployTxHashLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldDeployTxHash, v))
}

// DeployTxHashLTE applies the LTE predicate on the "deploy_tx_hash" field.
func DeployTxHashLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldDeployTxHash, v))
}

// DeployTxHashContains applies the Contains predicate on the "deploy_tx_hash" field.
func DeployTxHashContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldDeployTxHash, v))
}

// DeployTxHashHasPrefix applies the HasPrefix predicate on the "deploy_tx_hash" field.
func DeployTxHashHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldDeployTxHash, v))
}

// DeployTxHashHasSuffix applies the HasSuffix predicate on the "deploy_tx_hash" field.
func DeployTxHashHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldDeployTxHash, v))
}

// DeployTxHashIsNil applies the IsNil predicate on the "deploy_tx_hash" field.
func DeployTxHashIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldDeployTxHash))
}

// DeployTxHashNotNil applies the NotNil predicate on the "deploy_tx_hash" field.
func DeployTxHashNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldDeployTxHash))
}

// DeployTxHashEqualFold applies the EqualFold predicate on the "deploy_tx_hash" field.
func DeployTxHashEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldDeployTxHash, v))
}

// DeployTxHashContainsFold applies the ContainsFold predicate on the "deploy_tx_hash" field.
func DeployTxHashContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldDeployTxHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Account) predicate.Account {
	return predicate.Account(sql.NotPredicates(p))
}
