// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/byunyourim/stablecoinbc-adapter/ent/account"
	"github.com/byunyourim/stablecoinbc-adapter/ent/predicate"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChainID sets the "chain_id" field.
func (_u *AccountUpdate) SetChainID(v int64) *AccountUpdate {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableChainID(v *int64) *AccountUpdate {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *AccountUpdate) AddChainID(v int64) *AccountUpdate {
	_u.mutation.AddChainID(v)
	return _u
}

// SetAddress sets the "address" field.
func (_u *AccountUpdate) SetAddress(v string) *AccountUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAddress(v *string) *AccountUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetSalt sets the "salt" field.
func (_u *AccountUpdate) SetSalt(v string) *AccountUpdate {
	_u.mutation.SetSalt(v)
	return _u
}

// SetNillableSalt sets the "salt" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableSalt(v *string) *AccountUpdate {
	if v != nil {
		_u.SetSalt(*v)
	}
	return _u
}

// SetDeployed sets the "deployed" field.
func (_u *AccountUpdate) SetDeployed(v bool) *AccountUpdate {
	_u.mutation.SetDeployed(v)
	return _u
}

// SetNillableDeployed sets the "deployed" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableDeployed(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetDeployed(*v)
	}
	return _u
}

// SetDeployTxHash sets the "deploy_tx_hash" field.
func (_u *AccountUpdate) SetDeployTxHash(v string) *AccountUpdate {
	_u.mutation.SetDeployTxHash(v)
	return _u
}

// SetNillableDeployTxHash sets the "deploy_tx_hash" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableDeployTxHash(v *string) *AccountUpdate {
	if v != nil {
		_u.SetDeployTxHash(*v)
	}
	return _u
}

// ClearDeployTxHash clears the value of the "deploy_tx_hash" field.
func (_u *AccountUpdate) ClearDeployTxHash() *AccountUpdate {
	_u.mutation.ClearDeployTxHash()
	return _u
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdate) Mutation() *AccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(account.FieldChainID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(account.FieldChainID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(account.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Salt(); ok {
		_spec.SetField(account.FieldSalt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Deployed(); ok {
		_spec.SetField(account.FieldDeployed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeployTxHash(); ok {
		_spec.SetField(account.FieldDeployTxHash, field.TypeString, value)
	}
	if _u.mutation.DeployTxHashCleared() {
		_spec.ClearField(account.FieldDeployTxHash, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetChainID sets the "chain_id" field.
func (_u *AccountUpdateOne) SetChainID(v int64) *AccountUpdateOne {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableChainID(v *int64) *AccountUpdateOne {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *AccountUpdateOne) AddChainID(v int64) *AccountUpdateOne {
	_u.mutation.AddChainID(v)
	return _u
}

// SetAddress sets the "address" field.
func (_u *AccountUpdateOne) SetAddress(v string) *AccountUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAddress(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetSalt sets the "salt" field.
func (_u *AccountUpdateOne) SetSalt(v string) *AccountUpdateOne {
	_u.mutation.SetSalt(v)
	return _u
}

// SetNillableSalt sets the "salt" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableSalt(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetSalt(*v)
	}
	return _u
}

// SetDeployed sets the "deployed" field.
func (_u *AccountUpdateOne) SetDeployed(v bool) *AccountUpdateOne {
	_u.mutation.SetDeployed(v)
	return _u
}

// SetNillableDeployed sets the "deployed" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableDeployed(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetDeployed(*v)
	}
	return _u
}

// SetDeployTxHash sets the "deploy_tx_hash" field.
func (_u *AccountUpdateOne) SetDeployTxHash(v string) *AccountUpdateOne {
	_u.mutation.SetDeployTxHash(v)
	return _u
}

// SetNillableDeployTxHash sets the "deploy_tx_hash" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableDeployTxHash(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetDeployTxHash(*v)
	}
	return _u
}

// ClearDeployTxHash clears the value of the "deploy_tx_hash" field.
func (_u *AccountUpdateOne) ClearDeployTxHash() *AccountUpdateOne {
	_u.mutation.ClearDeployTxHash()
	return _u
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdateOne) Mutation() *AccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Account entity.
func (_u *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(account.FieldChainID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(account.FieldChainID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(account.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Salt(); ok {
		_spec.SetField(account.FieldSalt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Deployed(); ok {
		_spec.SetField(account.FieldDeployed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeployTxHash(); ok {
		_spec.SetField(account.FieldDeployTxHash, field.TypeString, value)
	}
	if _u.mutation.DeployTxHashCleared() {
		_spec.ClearField(account.FieldDeployTxHash, field.TypeString)
	}
	_node = &Account{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
