// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/byunyourim/stablecoinbc-adapter/ent/account"
	"github.com/byunyourim/stablecoinbc-adapter/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescDeployed is the schema descriptor for deployed field.
	accountDescDeployed := accountFields[3].Descriptor()
	// account.DefaultDeployed holds the default value on creation for the deployed field.
	account.DefaultDeployed = accountDescDeployed.Default.(bool)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[5].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
}
